### ISSUE TITLE
App manager error when run Cytoscape from command

### ISSUE THREAD

**Issue by yihangx** [cytoscape/js4cytoscape#27]
Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: TypeError: undefined is not an object (evaluating 'row.cells')
	at javafx.web@18.0.1/com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:160)
	at javafx.web@18.0.1/com.sun.webkit.dom.JSObject.callImpl(Native Method)
	at javafx.web@18.0.1/com.sun.webkit.dom.JSObject.call(JSObject.java:129)
	at edu.ucsf.rbvi.cyBrowser.internal.model.Bridge$CallbackObserver$1.run(Bridge.java:168)
	at javafx.graphics@18.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@18.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics@18.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

And sometimes update green arrow is not working. Maybe it is related to this error.

**Comment by AlexanderPico** [comment]
Sorting loops went one step too far. Fixed!
